#!/usr/bin/env bash

mkdir -p /var/lib/rainloop/data

shopt -s nullglob
shopt -s dotglob

declare need_setup_rainloop

rainloop_files=(/var/lib/rainloop/data/*)
(( ${#rainloop_files[*]} )) && need_setup_rainloop=0 || need_setup_rainloop=1

shopt -u nullglob
shopt -u dotglob

if [[ $need_setup_rainloop -eq 1 ]]; then
    rsync -av /usr/share/webapps/rainloop-default-data/ /var/lib/rainloop/data/
fi

exec s6-setuidgid http php-fpm -F
